{{- if .Values.secrets.mssql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mssql.name }}
  namespace: {{ .Values.kafkaConnect.namespace }}
type: Opaque
data:
  connection.password: {{ .Values.secrets.mssql.data.connection.password | b64enc | quote }}
{{- end }}

{{- if .Values.secrets.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3Sink.name }}-credentials
  namespace: {{ .Values.kafkaConnect.namespace }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.secrets.s3.data.aws.access.key.id | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secrets.s3.data.aws.secret.access.key | b64enc | quote }}
{{- end }}

